// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64
// +build arm64

package secexec

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpf_debugSecEvent struct {
	Meta struct {
		Op       uint8
		_        [3]byte
		Pid      uint32
		Tid      uint32
		Ppid     uint32
		Uid      uint32
		Auid     uint32
		NsPid    uint32
		NsPpid   uint32
		PidNsId  uint32
		_        [4]byte
		TimeNs   uint64
		CapEff   uint64
		CapInh   uint64
		CapPerm  uint64
		CgrpId   uint32
		NetNs    uint32
		CgrpName [128]uint8
		Comm     [16]uint8
	}
	Filename [256]uint8
	Buf      [2048]uint8
}

// loadBpf_debug returns the embedded CollectionSpec for bpf_debug.
func loadBpf_debug() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_debugBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_debug: %w", err)
	}

	return spec, err
}

// loadBpf_debugObjects loads bpf_debug and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_debugObjects
//	*bpf_debugPrograms
//	*bpf_debugMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_debugObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_debug()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_debugSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_debugSpecs struct {
	bpf_debugProgramSpecs
	bpf_debugMapSpecs
}

// bpf_debugSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_debugProgramSpecs struct {
	KprobeDoTaskDead     *ebpf.ProgramSpec `ebpf:"kprobe_do_task_dead"`
	SyscallEnterExecve   *ebpf.ProgramSpec `ebpf:"syscall_enter_execve"`
	SyscallEnterExecveat *ebpf.ProgramSpec `ebpf:"syscall_enter_execveat"`
}

// bpf_debugMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_debugMapSpecs struct {
	ActivePids *ebpf.MapSpec `ebpf:"active_pids"`
	Events     *ebpf.MapSpec `ebpf:"events"`
}

// bpf_debugObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_debugObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_debugObjects struct {
	bpf_debugPrograms
	bpf_debugMaps
}

func (o *bpf_debugObjects) Close() error {
	return _Bpf_debugClose(
		&o.bpf_debugPrograms,
		&o.bpf_debugMaps,
	)
}

// bpf_debugMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_debugObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_debugMaps struct {
	ActivePids *ebpf.Map `ebpf:"active_pids"`
	Events     *ebpf.Map `ebpf:"events"`
}

func (m *bpf_debugMaps) Close() error {
	return _Bpf_debugClose(
		m.ActivePids,
		m.Events,
	)
}

// bpf_debugPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_debugObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_debugPrograms struct {
	KprobeDoTaskDead     *ebpf.Program `ebpf:"kprobe_do_task_dead"`
	SyscallEnterExecve   *ebpf.Program `ebpf:"syscall_enter_execve"`
	SyscallEnterExecveat *ebpf.Program `ebpf:"syscall_enter_execveat"`
}

func (p *bpf_debugPrograms) Close() error {
	return _Bpf_debugClose(
		p.KprobeDoTaskDead,
		p.SyscallEnterExecve,
		p.SyscallEnterExecveat,
	)
}

func _Bpf_debugClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_debug_bpfel_arm64.o
var _Bpf_debugBytes []byte
