{
 "title": "Beyla",
 "tags": [
  "beyla",
  "ebpf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Beyla Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beyla_internal_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DaemonSet: Running pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{daemonset=~\"(beyla|grafana-k8s-monitoring-beyla)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OTEL metric exports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (beyla_otel_metric_exports_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OTEL trace exports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (beyla_otel_trace_exports_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Processes",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(process_name) (beyla_instrumented_processes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{job=\"default/beyla\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(process_command) (process_cpu_utilization_ratio{job=\"default/beyla\"})",
     "legendFormat": "{{process_command}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"default/beyla\"} | logfmt | component!=`BPFLogger`"
    }
   ]
  },
  {
   "title": "BPF Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{job=\"default/beyla\"} | logfmt | component=`BPFLogger`"
    }
   ]
  },
  {
   "title": "Application Errors",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{job=\"default/beyla\"} |= `ERROR`"
    }
   ]
  }
 ]
}